// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eupzhjktffzmzzcddemn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1cHpoamt0ZmZ6bXp6Y2RkZW1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4MzQ3OTMsImV4cCI6MjA4NjQxMDc5M30.rGLCYDRdbel6qFrTcqvJ4-OYl4htb25QkIDy93P4XxQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});